#!/bin/bash
# Starts the bathroom key web server and key_sensor
# Can add a soft link to your bin with ln -s path/to/bathroom-key ~/bin

ROOT=~/bathroom-key

# TODO(whiteside): implement a better way to stop and start both of these
# processes

cd $ROOT
sudo ./web_server.py > server.log 2>&1 &
sudo ./key_sensor.py > sensor.log 2>&1 &

# to force cleanup - sudo killall python -sSIGKILL
