#!/bin/bash
# Starts the bathroom key web server and key_sensor
# Can add a soft link to your bin with ln -s path/to/bathroom-key ~/bin

ROOT=~/bathroom-key

cd $ROOT
sudo ./web_server.py &
sudo ./key_sensor.py

# to force cleanup - sudo killall python
